# Generated by Django 5.0.7 on 2024-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRentalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_balance', models.IntegerField()),
                ('rental_income', models.ImageField(upload_to='')),
            ],
        ),
    ]
