# Generated by Django 5.0.7 on 2024-08-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_balancerentalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancerentalmodel',
            name='rental_income',
            field=models.IntegerField(),
        ),
    ]
